---
USER_AGENT:
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36'
BLACK_DOMAIN:
  - 'www.google.gf'
  - 'www.google.io'
  - 'www.google.com.lc'
  - 'scholar.google.cn'
PROXIES:
  http:
        'http://192.168.1.126:1080'
  https:
        'http://192.168.1.126:1080'

DOMAIN:
  'www.google.com'
URL_GOOGLE_NEWS:
  "https://{domain}/search?hl={language}&q={query}&btnG=Search&gbv=2&num=20&start={start}&source=lnms&tbm=nws"
URL_GOOGLE_SCHOLAR:
  "https://{domain}/scholar?&q={query}&hl={language}&as_sdt=0,5"
URL_GOOGLE_SCHOLAR_NEXT:
  "https://{domain}/scholar?start={start}&q={query}&hl=zh-CN&as_sdt=0,5"
URL_GOOGLE_SEARCH:
  "https://{domain}/search?hl={language}&q={query}&btnG=Search&gbv=1&num=20&start={start}"
COOKIES:
  'cookies_are':
    "APISID=NeZFvwIlSf_VFLLJ/AOXrafdbi6JV4sc64; SAPISID=5qcC8Xkb7UO3GcNM/AIrZPXgugYcCDpquH; SID=uwV2PDOC2LmzKo50QvpQ19IU0QLQfVaJGDyRRa9--0zos_5rj0RdrxHiphOvMjAlJ_fT2A.; GSP=IN=7e6cc990821af63:LD=zh-CN:CF=4:LM=1526451723:S=L63dTv7IZUmsfik0; 1P_JAR=2018-5-16-8; SIDCC=AEfoLeaD3P2TSefx6nJwwtNUJqHsJ4-tQfiEzmuKwrxHZcO6GJQXGYUFlyjxb2iE2u-xwNIRbzm2siRvgBC2"

consumer_key:
  '6dnvGmfdvUlpaeJfIvxAIPdmL'
consumer_secret:
  'zngKpEc6FCU3PpYg7tsqZhJfeFkiuAEL2efjOD1FKA1xeEnX3M'
access_token:
  '16390258-qtr59E8pKr5oLgsak3UjKH8KgkoUkWoNYvKoXeIWJ'
access_token_secret:
  'FN7gi5QrsGW4Qh6T7n1B96HuYqrYy42HnJb0MySxBUHI4'
